[package]
name = "cbor"
version = "3.0.0"
description = "A CBOR library for encoding and decoding CBOR bytes"
repository = "https://github.com/edjcase/motoko_cbor"
keywords = ["cbor", "encoding"]
license = "MIT"

[dependencies]
base = "0.14.14"
xtended-numbers = "0.4.0"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.14"
